### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Eun0**
Fix 
```ConvertPredictedTrqajectoryMarkers```
to 
```ConvertPredictedTrajectoriesMarkers```

### CODE REVIEW

**Comment by JWhitleyWork** [comment]
@Eun0 I see the typo that you mentioned. However, please leave the name the same other than fixing the extra `q` and you must also fix it in `op_ros_helpers/include/op_ros_helpers/op_ROSHelpers.h`. It is also used in `core_planning/op_local_planner/nodes/op_motion_predictor/op_motion_predictor_core.cpp` and must be changed there too. Finally, you must sign your commits (see the DCO check below for more details).

**Comment by Eun0** [comment]
Thanks for your kind comment.

The reason why I used ```ConvertPredictedTrajectories``` other than fixing the extra ```q``` is that the relative ros topic is ```/predicted_trajectories_rviz```. So what do you think of using the name I suggested?

I also fixed the typo in ```op_ros_helpers/include/op_ros_helpers/op_ROSHelpers.h```and I did DCO check.

After merging this pull request, I will fix ```core_planning/op_local_planner/nodes/op_motion_predictor/op_motion_predictor_core.cpp``` soon.

**Comment by JWhitleyWork** [comment]
It does look like there are multiple trajectories being published in a single message so I'm OK with the name change. Thanks for the fix! So that the repositories don't get out-of-sync, I will wait to merge this change until you have created the merge request for `core_planning`. The CI will fail on that request until this one is merged but I would feel better knowing that the request is at least created so we don't have to go hunt down why something is failing after we merge this one.

**Comment by Eun0** [comment]
Thank you for your guidance!

I also created the merge request for ```core_planning```.

**Pull request merged**
